FROM apache/airflow:slim-2.10.5-python3.11

USER root
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

USER airflow
RUN --mount=type=bind,source=uv.lock,target=uv.lock \
    --mount=type=bind,source=pyproject.toml,target=pyproject.toml \
    --mount=type=bind,source=README.md,target=README.md \
    uv pip install ".[celery]"
