dbt_redshift_analytics:
  outputs:
    dev:
      type: redshift
      method: iam
      host:         "{{ env_var('DBT_REDSHIFT_HOST') }}"
      port:         "{{ env_var('DBT_REDSHIFT_PORT', 5439) | as_number }}"
      dbname:       "{{ env_var('DBT_REDSHIFT_TARGET_DATABASE') }}"
      schema:       "{{ env_var('DBT_REDSHIFT_TARGET_SCHEMA') }}"
      user:         "{{ env_var('DBT_REDSHIFT_USER', '') }}"      # ignored on Redshift Serverless
      iam_profile:  "{{ env_var('DBT_REDSHIFT_IAM_PROFILE') }}"   # reads profile defined in ~/.aws/credentials
      threads: 4

    prod:
      type: redshift
      method: iam
      host:         "{{ env_var('DBT_REDSHIFT_HOST') }}"
      port:         "{{ env_var('DBT_REDSHIFT_PORT', 5439) | as_number }}"
      dbname:       "{{ env_var('DBT_REDSHIFT_TARGET_DATABASE') }}"
      schema:       "{{ env_var('DBT_REDSHIFT_TARGET_SCHEMA') }}"
      user:         "{{ env_var('DBT_REDSHIFT_USER', '') }}"      # ignored on Redshift Serverless
      iam_profile:  "{{ env_var('DBT_REDSHIFT_IAM_PROFILE') }}"   # reads profile defined in ~/.aws/credentials
      threads: 4

  target: dev
