x-postgres-image: &postgres-image postgres:${POSTGRES_VERSION:-18-alpine}

services:
  nyc-tlc-db:
    image: *postgres-image
    container_name: nyc-tlc-db
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'nyc_tlc'
    ports:
      - '5432:5432'
    volumes:
      - vol-nyc-tlc-db:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: on-failure

  nyc-tlc-cli:
    image: nyc-tlc-cli:latest
    container_name: nyc-tlc-cli
    build:
      context: .
      dockerfile: Dockerfile
    pull_policy: build
    environment:
      DB_HOST: 'nyc-tlc-db'
      DB_USERNAME: 'postgres'
      DB_PASSWORD: 'postgres'
      DB_NAME: 'nyc_tlc'
    volumes:
      - ./datasets.yml:/app/datasets.yml
    depends_on:
      nyc-tlc-db:
        condition: service_healthy

volumes:
  vol-nyc-tlc-db:
    name: vol-nyc-tlc-db
